routes/book.py
from flask import Blueprint, render_template, Flask, session
from bson import ObjectId
from routes.connection import mongo

book_bp = Blueprint("book", __name__)


@book_bp.route("/book/<book_id>", methods=["GET"])
def book(book_id):
    try:
        found_book = mongo.db.books.find_one({"_id": ObjectId(book_id)})
        find_review = mongo.db.reviews.find({"book_id": found_book["_id"]})
        find_review = list(find_review)

        score = found_book["score"]
        print(score)
        if found_book and find_review:
            print("Book found and review")

        print("Connection successful, searched book found.")
        return render_template(
            "book.html",
            title="book.name",
            book=found_book,
            review=find_review,
            score=score,
        )

    except Exception as e:
        print(f"Connection in book failed: {e}")
        return render_template(
            "book.html", title="Book", error="Unable to connect to the database."
        )

routes/login.py
from flask import (
    render_template,
    Blueprint,
    json,
    request,
    url_for,
    redirect,
    jsonify,
    session,
)
from werkzeug.security import generate_password_hash, check_password_hash
from routes.connection import mongo


login_bp = Blueprint("login", __name__)


@login_bp.route("/register", methods=["GET"])
def register():
    print("Registration page opened")
    return render_template("register.html", title="Login Page")


@login_bp.route("/register", methods=["POST"])
def get_register():
    try:
        name = request.form.get("name")
        email = request.form.get("email")
        pwd = request.form.get("password")
        hashed_pwd = generate_password_hash(pwd)

        mongo.db.users.insert_one({"name": name, "email": email, "pwd": hashed_pwd})
        print("Successfully registered")
        return redirect(url_for("home.home"))

    except Exception as e:
        print(f"Registration error: {e}")
        return redirect(url_for("home.home"))


@login_bp.route("/login", methods=["GET"])
def login():
    print("Login page loaded")
    return render_template("login.html", title="Login Page")


@login_bp.route("/get_login", methods=["POST"])
def get_login():
    try:
        email = request.json.get("email")
        pwd = request.json.get("pwd")
        user = mongo.db.users.find_one({"email": email})
        if not user:
            return jsonify({"exists": bool(user), "pass": False})

        if not check_password_hash(user["pwd"], pwd):
            return jsonify({"exists": False, "pwd": True})

        session["username"] = user["name"]
        session["email"] = user["email"]
        print(session["username"])
        print("Logged in successfully")
        return jsonify({"success": True, "redirect": url_for("home.home")})

    except Exception as e:
        print(f"Error in login: {e}")
        return jsonify({"sucess": False, "redirect": url_for("login.login")})


@login_bp.route("/logout", methods=["GET"])
def logout():
    session.clear()
    return redirect(url_for("home.home"))

routes/review.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, session
from bson import ObjectId
from routes.connection import mongo

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.sentiment import SentimentIntensityAnalyzer
import string

nltk.download('punkt_tab')

review_bp = Blueprint("review", __name__)

@review_bp.route("/review/<book_id>", methods=['GET'])
def review(book_id):
    try:
        review_book = mongo.db.books.find_one({'_id': ObjectId(book_id)})
        if session['username']:
            rev = mongo.db.reviews.find_one({'book_id': ObjectId(book_id), 'email': session['email']})
            print(rev)
            if rev:
                return render_template("review.html", title="review_book.name", book=review_book , book_id=book_id, rev = rev)
        
        return render_template("review.html", title="review_book.name", book=review_book , book_id=book_id)

    
    except Exception as e:
        print(f"Connection fail: {e}")
        return render_template("review.html", title="review_book.name", book=review_book , book_id=book_id)


@review_bp.route("/submit/<book_id>", methods=['GET', 'POST'])
def submit(book_id):
    try:
        email = session['email']
        name = session['username']
        review_msg = request.form.get("re-review")
        final_score = update_score(review_msg)
        print("Here")
        mongo.db.reviews.insert_one({'book_id': ObjectId(book_id), 'name': name, 'email': email, 'review': review_msg, 'score': final_score})

        update_book_score(book_id)

        print("Connection successful in updating mongo")
        return redirect(url_for('book.book', book_id=book_id)) 
    
    except Exception as e:
        print(f"Error detected: {e}")
        return redirect(url_for('book.book', book_id=book_id))


@review_bp.route("/check-email", methods=['POST'])
def email_check():
    email = request.json.get('email')
    book = request.json.get('check_book')
    exists = mongo.db.reviews.find_one({'email': email, 'book_id': ObjectId(book)})

    return jsonify({'exists': bool(exists)})

@review_bp.route('/re-review/<book_id>', methods=['GET', 'POST'])
def re_review(book_id):
    try:
        msg = request.form.get('re-review')

        score = update_score(msg)

        user = mongo.db.users.find_one({'name': session['username']})
        mongo.db.reviews.update_one({'email': user['email'], 'book_id': ObjectId(book_id)}, {'$set': {'score': score, 'edit': True, 'review': msg}})

        update_book_score(book_id)
        print("Book review updated")
        return redirect(url_for('home.dash'))
    
    except Exception as e:
        print(f"Re-review error: {e}")
        return redirect(url_for('home.dash'))



def update_score(rev):
    nltk.data.path.append('.venv/nltk_data')

    text = rev
    text = text.lower()

    text = text.translate(str.maketrans('', '', string.punctuation))
    words = word_tokenize(text)
    stop_words = set(stopwords.words('english'))
    cleaned_words = [word for word in words if word not in stop_words]
    
    text = ' '.join(cleaned_words)
    sia = SentimentIntensityAnalyzer()
    score = sia.polarity_scores(text)
    scaled = 1 + ((score['compound'] + 1) / 2) * 4
    scaled = round(scaled, 1)
    return scaled

def update_book_score(book_id):
    pipeline = [
        {"$match": {"book_id": ObjectId(book_id)}},
        {"$group": {"_id": None, "avg": {"$avg": "$score"}}}
    ]
    score = list(mongo.db.reviews.aggregate(pipeline))
    final_score = score[0]['avg']
    final_score = round(final_score, 1)
    print(type(final_score))
    print(final_score)
    mongo.db.books.update_one({'_id': ObjectId(book_id)}, {'$set': { 'score': final_score}})
    print("Book score updated")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <title>{% block title %}That's The Book?{% endblock %}</title>
    {% block head %} {% endblock %}
</head>
<body>
    <header>
        <div class="logo">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Book Image">
        </div>

        <nav>
            <li><a href="{{ url_for('home.home')}}">Home</a></li>
            {% if session.username %}
                <li><a href="{{ url_for('home.dash') }}">{{session.username}}</a></li>
                <li><a href="{{ url_for('login.logout')}}">Logout</a></li>
            {% else %}
                <li><a href="{{ url_for('login.register')}}">Register</a></li>
                <li><a href="{{ url_for('login.login')}}">Login</a></li>
            {% endif %}


        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <div class="footer-content">
            <div class="site-iden">
                <img src="{{ url_for('static', filename='images/logo.png')}}" alt="Site Logo">
            </div>
            <ul class="footer-sitemap">
                <h2>SiteMap</h2>
                <li><a href="{{ url_for('home.home') }}">Home</a></li>
                {% if session.username %}
                    <li><a href="{{ url_for('home.dash') }}">{{session.username}}</a></li>
                    <li><a href="{{ url_for('login.logout') }}">Logout</a></li>
                {% else %}
                    <li><a href="{{ url_for('login.register') }}">Register</a></li>
                    <li><a href="{{ url_for('login.login') }}">Login</a></li>
                {% endif %}
            </ul>
            <form class="footer-form" method="post" action="#">
                <label for="book_name">Book Name</label>
                <input type="text" id="book_name" name="book_name" required>
                <label for="author">Author</label>
                <input type="text" id="author" name="author" required>
                <button type="submit">Suggest Book</button>
            </form>
        </div>
    </footer>

</body>
</html>

templates/book.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/product.css')}}">
{% endblock %}


{% block content %}
    <div class="product-page">
        <div class="book-image">
            <img src="{{ url_for('static', filename=book.image) }}" alt="Book Cover">
        </div>

        <div class="book-details">
            <h1>{{book.name}}</h1>
            <p><strong>Author:</strong> {{book.author}}</p>
            <p><strong>Publication:</strong> {{book.publish}}</p>
            <p><strong>Year:</strong> {{book.year}}</p>
            <p><strong>Rating:</strong> 
                {% set full_stars = score | int %}
                {% set has_half = (score - full_stars) > 0 %}
                {% set empty_stars = (4 - full_stars) if has_half else (5 - full_stars) %}

                {% for _ in range(full_stars) %}
                    <span class="filled">&#9733;</span>
                {% endfor %}

                {% if has_half %}
                    <span class="half-filled">&#9733;</span>
                {% endif %}

                {% for _ in range(empty_stars) %}
                    <span>&#9733;</span>
                {% endfor %}
                <span class="rating-val">({{ score }})</span>
            </p>
            {% if session.username %}
                <a href="{{ url_for('review.review', book_id=book._id)}}" class="review-button">Leave a Review</a>
                {% else %}
                <a href="{{ url_for('login.login')}}" class="review-button">Login to Review</a>
            {% endif %}
        </div>
    </div>

    <div class="feedback-section">
        <h2>What People think about it...</h2>
        <div class="feedback-list">
            {% for rev in review[:5] %}
            <div class="feedback-item">
                <p><strong>{{rev.name}}:</strong> <span style="color: rgb(150, 150, 1);">{{rev.score}}</span></p>
                <br>
                <p>
                    {% if rev.edit %}
                    <span>Edited:</span>
                    {% endif %}
                    "{{rev.review}}"
                </p>
            </div>
            {% endfor %}

            {% for rev in review[5:] %}
            <div class="feedback-item hidden">
                <p><strong>{{rev.name}}:</strong> <span style="color: rgb(150, 150, 1);">{{rev.score}}</span></p>
                <br>
                <p>
                    {% if rev.edit %}
                    <span>Edited:</span>
                    {% endif %}
                    "{{rev.review}}"
                </p>
            </div>
            {% endfor %}

        </div>
        <button id="show-more-btn">Show More</button>
    </div>

    <script>
        document.getElementById('show-more-btn').addEventListener('click', function () {
            const hiddenItems = document.querySelectorAll('.feedback-item.hidden');
            hiddenItems.forEach(item => item.classList.remove('hidden'));
            this.style.display = 'none';
        });
    </script>

{% endblock %}

templates/books.html
<div class="books">
    {% for book in books %}
    <div class="item">
        <div class="image">
            <img src="{{url_for('static', filename=book.image)}}" alt="{{book.name}}">
        </div>
        <div class="desc">
            <h2>{{book.name}}</h2>
            <div class="review">
                <p><strong>Rating:</strong> 
                {% set full_stars = book.score | int %}
                {% set has_half = (book.score - full_stars) > 0 %}
                {% set empty_stars = (4 - full_stars) if has_half else (5 - full_stars) %}

                {% for _ in range(full_stars) %}
                    <span class="filled">&#9733;</span>
                {% endfor %}

                {% if has_half %}
                    <span class="half-filled">&#9733;</span>
                {% endif %}

                {% for _ in range(empty_stars) %}
                    <span>&#9733;</span>
                {% endfor %}
                </p>
                <p><strong>Rating: </strong> <span style="font-weight: lighter; color: rgb(150, 150, 0);">{{ book.score }}</span></p>
            </div>
            <a href="{{ url_for('book.book', book_id=book._id ) }}"><button>Know More</button></a>
        </div>
    </div>
    
    {% endfor %}
</div>

templates/dash.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dash.css')}}">
{% endblock %}



{% block content %}

<div class="page-container">
    <div class="container">
        <h1 style="text-align: center;">Books You've Liked</h1>
        {% for book in books %}
        <div class="book-card">
            <div class="image">
                <img src="{{ url_for('static', filename=book.image) }}" alt="">
            </div>
            <div class="desc">
                <h2>{{ book.name }}</h2>
                <p><strong>Author: </strong>{{ book.author }}</p>
                {% for rev in reviews %}
                    {% if book._id == rev.book_id %}
                        <p><strong>Your Review: </strong> "{{ rev.review }}"</p>
                        {% set old_rev = rev.review %}
                    {% endif %}
                {% endfor %}

                <form action="{{ url_for('review.re_review', book_id=book._id) }}" method="post" class="rev-hidden revForm">
                    <textarea name="re-review" class="re-review rev-hidden" cols="50" rows="5" placeholder="Edit your review" required>{{ old_rev }}</textarea>
                    <br>
                    <input class="rev-hidden rev-sub" type="submit" value="Submit">
                </form>
                <button class="re-review-btn">Re-Review</button>

    
            </div>
        </div>
    
        {% endfor %}
    </div>
</div>

<script>
    const butt = document.querySelectorAll('.re-review-btn');
    const tt = document.querySelectorAll('.re-review');
    const bb = document.querySelectorAll('.rev-sub');
    const pp = document.querySelectorAll('.revForm');

    butt.forEach((but, index)=> {
        but.addEventListener('click', ()=> {
            tt[index].classList.remove('rev-hidden');
            bb[index].classList.remove('rev-hidden');
            pp[index].classList.remove('rev-hidden');
    
            tt[index].style.display = 'block';
            bb[index].style.display = 'block';
            pp[index].style.display = 'block';
    
            but.style.display = 'none';
        });

    });
    
</script>



{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/home.css')}}">
{% endblock %}


{% block content %}

    <div class="page-container">
        <div class="container">
                <h1>Our Top Picks</h1>
            {% include "books.html" %}
        </div>
    </div>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css')}}">
{% endblock %}



{% block content %}
  <div class="page-container">
    <div class="container">
      <h2>Sign In</h2>
      <form id="registerForm" method="post">
        <input type="email" id="email" name="email" placeholder="Email" required>
        <p class="msg-email hide-email" style="font-size: 0.8em; color: red;"></p>

        <input type="password" id="pwd" name="pwd" placeholder="Password" required>
        <p class="msg-pwd hide-email" style="font-size: 0.8em; color: red;"></p>

        <input type="submit" value="Register" class="button">
      </form>
      <p>New here? <a href="{{ url_for('login.register') }}">Register Now</a></p>
    </div>

  </div>


  <script>
    document.getElementById('registerForm').addEventListener('submit', async (e) => {
        e.preventDefault();
        const email = document.getElementById('email').value;
        const pwd = document.getElementById('pwd').value;

        const res = await fetch ('/get_login', {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({email, pwd})
        });

        const data = await res.json();
        const msg_email = document.querySelector('.msg-email');
        const msg_pwd = document.querySelector('.msg-pwd');

        if (data.exists) {
            msg_email.textContent = "Email does not exist";
            msg_email.classList.remove("hide-email");
            msg_email.style.display = "block";
        }
        
        else if (data.pass) {
            msg_pwd.textContent = "Password incorrect";
            msg_pwd.classList.remove("hide-email");
            msg_pwd.style.display = "block";
        }

        if (data.success) {
          window.location.href = data.redirect;
        }
        else {
          alert("An error occurred during login. Please try again!")
          window.location.href = data.redirect;
        }

    });
    
  </script>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css')}}">
{% endblock %}



{% block content %}
  <div class="page-container">
    <div class="container">
      <h2>Sign Up</h2>
      <form action="{{ url_for('login.get_register')}}" id="registerForm" method="post">
        <input type="text" id="name" name="name" placeholder="Full Name" required>
        <input type="email" id="email" name="email" placeholder="Email" required>
        <input type="password" id="password" name="password" placeholder="Password" required>
        <p id="msg" style="font-size: 0.8em; color: red;"></p>
        <input type="password" id="confirmPassword" name="confirmPassword" placeholder="Confirm Password" required>
        <input type="submit" value="Register" class="button">
      </form>
    </div>

  </div>


  <script>
    document.getElementById('registerForm').addEventListener('submit', function(e) {
      
      const name = document.getElementById('name').value.trim();
      const email = document.getElementById('email').value.trim();
      const password = document.getElementById('password').value;
      const confirmPassword = document.getElementById('confirmPassword').value;
      const message = document.getElementById('msg')
      
      if (password !== confirmPassword) {
        e.preventDefault();
        message.textContent = "Passwords do not match!";
        return;
    }
    console.log("This is definitely happening");
    console.log(name);

    alert("Registration Successfull!");
    });

  </script>

{% endblock %}

templates/review.html
{% extends "base.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/review.css') }}">
{% endblock %}

{% block content %}

    <div class="review-container">
        <div class="review-image">
            <img src="{{ url_for('static', filename=book.image) }}" alt="{{book.name}}">
            <h2>{{book.name}}</h2>
            <h3>{{book.author}}</h3>
        </div>

        <div class="review-form">
            <h1>Tell us what you think</h1>
            <form 
                {% if rev %}
                    action="{{ url_for('review.re_review', book_id=book._id)}}" 
                {% else %}
                    action="{{ url_for('review.submit', book_id=book._id)}}" 
                {% endif %}
            class="revForm" method="post">
                <label for="name">Name</label>

                {% if session.username %}
                    <input type="text" name="name" id="name" value="{{ session.username }}" disabled>
                {% else %}
                    <input type="text" name="name" id="name">
                {% endif %}

                <label for="email">Email</label>
                <span class="msg hide-email"></span>

                {% if session.username %}
                    <input type="email" name="email" id="email" value="{{ session.email }}" disabled>
                {% else %}
                    <input type="email" name="email" id="email">
                {% endif %}

                {% if rev %}
                    <label for="review">Edit Review <br></label>
                    <textarea name="re-review" id="review" cols="50" rows="10">{{ rev.review }}</textarea>
                {% else %}
                    <label for="review">Review <br></label>
                    <textarea name="re-review" id="review" cols="50" rows="10"></textarea>
                {% endif %}

                <input type="submit" value="Submit" class="submit">
            </form>
        </div>

    </div>

    <!-- <script>
        let emailValid = false;

        document.querySelector('.revForm').addEventListener('submit', async (e) => {
            e.preventDefault()
            const email = document.getElementById('email').value;
            let check_book = "{{ book_id }}";
            const res = await fetch('/check-email', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({ email, check_book })
            });
            const data = await res.json();
            const msg = document.querySelector('.msg');
            if (data.exists) {
                msg.textContent = "Email already registered!";
                msg.classList.remove("hide-email");
                msg.style.display = "block";
            } else {
                msg.style.display = "none";
                alert("Review recieved! Thank you!");
                e.target.submit();
            }
        });
</script> -->

{% endblock %}